### ISSUE TITLE
Incorrect parsing of java 1.8 version in 0.3.1

### ISSUE THREAD

**Issue by andersgs** [rrwick/Unicycler#17]
Hi Ryan.

When running `java -version` on our system we get the following:

    openjdk version "1.8.0_131"
    OpenJDK Runtime Environment (build 1.8.0_131-b11)
    OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

In your current code, it parses out the version to be `openjdk`, leading `unicycler` to fail the java  dependency with a `?` and the comment `too old`.

Perhaps some regex would help here:

    import re
    # some subprocess code here to run java -version and capture stdout to a 
    # variable called java_version
    java_pat = re.compile(r'([01])\.([1-8])\.([0-9])_([0-9]{0,3})')
    obs_java_version = java_pat.findall(java_version.decode())
    # On our system, you get two hits here:
    # [('1', '8', '0', '131'), ('1', '8', '0', '131')]
    # Some further processing of the output from java -version to pick out just
    # the first line before applyting the regex might work best. But, each tuple 
    # already has your major and sub-versions already parsed out.

Cheers.

A.

**Comment by andersgs** [comment]
I have monkey patched my version with the following code:

```
def java_path_and_version(java_path):
    java_path = shutil.which(java_path)
    if java_path is None:
        return '', '', 'not found'
    java_pat = re.compile(r'([01])\.([1-8])\.([0-9])_([0-9]{0,3})')
    command = [java_path, '-version']
    process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    out, _ = process.communicate()
    version = java_pat.findall(out.decode())[0]

    major_version,minor_version,sub_version,fine_version = version

    # Make sure Java is 1.7+
    try:
        major_version = int(major_version)
        if major_version < 1:
            status = 'too old'
        else:
            minor_version = int(minor_version)
            if minor_version < 7:
                status = 'too old'
            else:
                status = 'good'
    except (ValueError, IndexError):
        version, status = '?', 'too old'

    return java_path, "{major}.{minor}".format(major = major_version,minor = minor_version), status
```

It works, but there is probably a more elegant way of doing this...

**Comment by caonetto** [comment]
HI Anders,
Could I get some assistance on how to monkey patch my version?

Thanks!

Cris.

**Comment by rrwick** [comment]
Thanks, this should now work the current version (v0.4.0). I just added a pretty simplistic fix: [checking for "openjdk" as well as "java"](https://github.com/rrwick/Unicycler/blob/a492ee297e2b4ffb69c2d2d4b11408989572e8a9/unicycler/misc.py#L959-L960).

I'll assume it works and close this issue, but let me know if anything's still not right!

**Comment by A-BN** [comment]
Hello,
First I'd like to thank you for all your work on `unicycler` and other software (everything in _Wick et al., Microbial Genomics 2017_ in fact).

On the matter of this issue_17, after installing the open-jdk version 9 on ubuntu, we still have this error because `java -version` returns `openjdk version "9-internal"` and is not parsed correctly.

Cheers,

A-BN
